# Generated by Django 2.2 on 2020-04-29 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, upload_to='Image/Profile/')),
                ('dob', models.DateField(auto_now_add=True)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('user_ip', models.GenericIPAddressField()),
                ('user_browser', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
