# Generated by Django 2.2 on 2020-04-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200429_2032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='UserDetails',
        ),
    ]
