# Generated by Django 2.2 on 2020-04-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200429_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
