# Generated by Django 2.2 on 2020-05-01 13:18

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0004_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AboutCMS',
            },
        ),
        migrations.CreateModel(
            name='BaseCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.ImageField(blank=True, upload_to='CMS/BaseHTML/')),
                ('logo', models.ImageField(blank=True, upload_to='CMS/BaseHTML/')),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('linked_in', models.TextField()),
                ('instagram', models.TextField()),
            ],
            options={
                'db_table': 'BaseCMS',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user_ip', models.GenericIPAddressField()),
                ('user_browser', models.CharField(default='', max_length=100)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='CourseCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('sub_heading', models.TextField()),
            ],
            options={
                'db_table': 'CourseCMS',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fees', models.IntegerField(default=100)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('timing', models.CharField(default='7PM - 1AM', max_length=20)),
                ('question', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('solution', models.TextField(default='')),
                ('i_o', models.TextField(default='')),
                ('impression', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='HomeCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_message', models.TextField()),
                ('course_heading_main', models.TextField()),
                ('course_heading_child', models.TextField()),
            ],
            options={
                'db_table': 'HomeCMS',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='CMS/About/Portfolio/')),
            ],
            options={
                'db_table': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_browser', models.CharField(default='', max_length=100)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
            options={
                'db_table': 'Subscriber',
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Course/Screenshot/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Courses')),
            ],
            options={
                'db_table': 'Screenshots',
            },
        ),
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, upload_to='Course/CoverPhoto/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Courses')),
            ],
            options={
                'db_table': 'CoverPhoto',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_browser', models.CharField(default='', max_length=100)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Courses')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
