# Generated by Django 2.2 on 2020-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200501_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fees',
            field=models.FloatField(default=100.0),
        ),
    ]
