# Generated by Django 2.2 on 2020-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200501_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcms',
            name='profile_iamge',
            field=models.ImageField(blank=True, default='', upload_to='CMS/About/AdminProfileImage/'),
        ),
    ]
