# Generated by Django 2.2 on 2020-05-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_aboutcms_profile_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcms',
            old_name='profile_iamge',
            new_name='profile_image',
        ),
    ]
