# Generated by Django 2.2 on 2020-05-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200502_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
