# Generated by Django 2.2 on 2020-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200502_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecms',
            name='page_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
