# Generated by Django 2.2 on 2020-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20200823_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
