# Generated by Django 2.2 on 2020-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200823_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(help_text='Topic Name', max_length=255),
        ),
    ]
