# Generated by Django 2.2 on 2020-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200823_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='author',
            field=models.CharField(help_text='Author Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tag',
            field=models.CharField(help_text='Tag Name', max_length=20),
        ),
    ]
