# Generated by Django 2.2 on 2020-08-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200823_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCMS',
        ),
    ]
